# Generated by Django 2.1.7 on 2019-03-19 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_movrotativo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movrotativo',
            old_name='checkount',
            new_name='checkout',
        ),
    ]
